Rfc 335
rrousselGit/river_pod pull request #462
Opened 2021-04-24 17:22 UTC by rrousselGit

Implements #335 

TODO:

- [x] Update Consumer/ConsumerWidget
- [ ] Remove useProvider
- [ ] Add HookConsumer/HookConsumerWidget
- [x] update docs to use new syntax (flutter_riverpod)
- [ ] update docs to use new syntax (hooks_riverpod)
- [ ] update "reading" doc
- [ ] implement ref.listen

2021-04-26 08:45 UTC, ResoDev commented
Hello! I don't see anything like "deprecate `context.read(provider)`" in the checklist of this PR. Does that mean that `ref.read(provider)` won't be implemented?

2021-04-26 08:54 UTC, rrousselGit commented
Oh I just forgot to add it to the list @ResoDev

2021-04-26 17:41 UTC, TimWhiting commented
Will you also be deprecating context.refresh -> ref.refresh?

2021-04-26 17:56 UTC, rrousselGit commented
Yes

And remove `ref.container` too

2021-04-28 17:11 UTC, TimWhiting reviewed
Changes in `riverpod_cli` should be reverted.

2021-05-01 18:53 UTC, kranfix commented on packages/flutter_riverpod/lib/src/consumer.dart
> +// ignore: one_member_abstracts
@rrousselGit I think there should exist a `ProviderReferenceBase`. Then `ProviderReference` and `WidgetReference` must extend it becase they will have a common API.

2021-05-04 10:26 UTC, SalahAdDin commented
What's about the following?

> Avoid calling `context.read` inside the build method of a Widget.
> If you want to optimize rebuilds, extract the value listened in a Provider instead.

2021-05-05 00:26 UTC, rrousselGit commented
> What's about the following?
> 
> > Avoid calling `context.read` inside the build method of a Widget.
> > If you want to optimize rebuilds, extract the value listened in a Provider instead.

That is going to stay.

2021-05-05 02:04 UTC, tbm98 commented
> > What's about the following?
> > > Avoid calling `context.read` inside the build method of a Widget.
> > > If you want to optimize rebuilds, extract the value listened in a Provider instead.
> 
> That is going to stay.

No. It should be modify if we have `ref.watch(provider.select)`

2021-05-05 03:19 UTC, rrousselGit commented
I'm not following.

Why would select invalidate this warning?

2021-05-05 03:24 UTC, tbm98 commented
> Avoid calling context.read inside the build method of a Widget.

it's fine.

but 
>If you want to optimize rebuilds, extract the value listened in a Provider instead.

we can do with ref.watch(provider.select) without extract to new provider

2021-05-05 09:02 UTC, rrousselGit commented
Oh you are correct. My bad

2021-05-24 02:31 UTC, kranfix requested changes

2021-05-24 02:31 UTC, kranfix commented on packages/hooks_riverpod/CHANGELOG.md
>        final value = watch(myProvider);
This line must be `final value = ref.watch(myProvider);`

2021-06-20 15:39 UTC, TimWhiting commented
#530 should fix CI for this branch

2021-06-20 19:11 UTC, rrousselGit commented
Let's merge this, make a dev release, and do the remaining tasks in a separate PR

2021-06-20 19:11 UTC, merged