Have WidgetRef implement Ref
rrousselGit/river_pod pull request #996
Opened 2021-12-09 03:40 UTC by tim-smart

This enables for a common base for all `Ref` types, which allows for easier dependency injection.

2021-12-09 09:45 UTC, rrousselGit commented on packages/flutter_riverpod/lib/src/consumer.dart
> +    bool fireImmediately,
The prototype of `listen` should not change. `fireImmediately` is not supported, and there is no purpose in exposing the subscription

2021-12-09 09:45 UTC, rrousselGit commented on packages/flutter_riverpod/lib/src/consumer.dart
> +  void onDispose(void Function() cb) => throw UnimplementedError();
This shouldn't exist

2021-12-09 09:47 UTC, rrousselGit requested changes
Thanks.

But they currently don't share a common interface because they work slightly differently (such as no `onDispose` and a different `listen`).

2021-12-09 20:16 UTC, tim-smart commented
> Thanks.
> 
> But they currently don't share a common interface because they work slightly differently (such as no `onDispose` and a different `listen`).

I have added `FrameworkRef` (not sure about the name) which adds `onDispose` and the `listen` variant on top of the `Ref` base type.

With the reduced API surface of `Ref`, `WidgetRef` can now implement it with minimal changes.

2021-12-09 20:21 UTC, rrousselGit commented
We can't change the API exposed by `Ref`. That would be breaking

But before that, could you explain the use-case for a common interface between both refs?

2021-12-09 21:08 UTC, tim-smart commented
> We can't change the API exposed by `Ref`. That would be breaking
> 
> But before that, could you explain the use-case for a common interface between both refs?

OK, we could have a `BaseRef` and keep the `Ref` interface the same?

My use case, notice the use of ref in both the widget side and provider side:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// Posts type and repo
typedef Post = Map<String, dynamic>;

class PostsRepo {
  Future<List<Post>> list() async => [];
}

final postsRepoProvider = Provider((ref) => PostsRepo());

// Business logic side
typedef PostAction = Future<List<Post>> Function(List<Post> currentState);

class PostActions {
  static PostAction fetch(Ref ref) => (state) => ref
      .read(postsRepoProvider)
      .list()
      .then((newPosts) => [...state, ...newPosts]);

  static PostAction clear() => (state) => Future.value([]);
}

// Thing that dispatches actions.
// Would actually be a package like `bloc_stream`.
class PostDispatcher {
  void add(PostAction action) {}
}

final postDispatcherProvider = Provider((ref) {
  final dispatcher = PostDispatcher();

  // Initial fetch
  dispatcher.add(PostActions.fetch(ref));

  return dispatcher;
});

class PostsList extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final dispatcher = ref.watch(postDispatcherProvider);
    // In a hook or something
    dispatcher.add(PostActions.fetch(ref));

    return ListView.builder(itemBuilder: itemBuilder);
  }
}

```

2021-12-09 21:23 UTC, rrousselGit commented
Why not make `PostAction` take the ref on top of the state?


```dart
static fetch() => (state, ref) => ref.read(foo).then(..)
```

The dispatcher should be able to have/pass the ref

```dart
class PostDispatcher {
  final Ref _ref;
  void add(PostAction action) {
    action(getState(), _ref);
  }
}

final postDispatcherProvider = Provider((ref) {
  final dispatcher = PostDispatcher(ref);
  ...
});
```

2021-12-09 21:51 UTC, tim-smart commented
> Why not make `PostAction` take the ref on top of the state?
> 
> ```dart
> static fetch() => (state, ref) => ref.read(foo).then(..)
> ```
> 
> The dispatcher should be able to have/pass the ref
> 
> ```dart
> class PostDispatcher {
>   final Ref _ref;
>   void add(PostAction action) {
>     action(getState(), _ref);
>   }
> }
> 
> final postDispatcherProvider = Provider((ref) {
>   final dispatcher = PostDispatcher(ref);
>   ...
> });
> ```

The shape of `PostAction` is determined by a dependency in this case, and the dependency is un-aware of the riverpod package.

The goal is to have the actions themselves declare their dependencies, rather than the state machine.

2021-12-09 22:28 UTC, rrousselGit commented
> The shape of PostAction is determined by a dependency in this case, and the dependency is un-aware of the riverpod package.

Then make a wrapper around that dependency to make your actions Riverpod-aware. There is most definitely an alternative solution that does not involve a common base-class between all refs.

Like:

```dart
class MyDispatcher {
  Dispatcher _dispatcher;
  Ref _ref;
  
  void add(PostAction action) {
    _dispatcher.add(action);
  }
  
  void addRiverpodAction(RiverpodAction action) {
    add((state) => action(state, _ref));
  }
}
```

`WidgetRef` and `Ref` are not interchangeable. They have different constraints. 

This is the wrong abstraction to the problem. It could cause tricky bugs or break tooling

2021-12-09 22:36 UTC, tim-smart commented
OK, fine - haha.

They might have different constraints but they also have a lot of overlap (`read` / `watch` / `refresh`), and at the end of the day have a similar purpose - "Get me access to my stuff please".

The solution I'll probably adapt is to pass the `Ref.read` function around, as the type signature is the same for both ref types.

2021-12-09 22:36 UTC, closed without merging

2021-12-09 22:46 UTC, tim-smart commented
Quick follow-up, passing the `read` function itself is working well.

If anyone ever comes across this and is looking for a solution, then here is what I came up with:

```dart
import 'package:hooks_riverpod/hooks_riverpod.dart';

typedef RefRead = T Function<T>(ProviderBase<T> provider);
```

You can then use `RefRead` in places that need to pull in dependencies.

2021-12-09 23:28 UTC, rrousselGit commented
Passing `read` is definitely less harmful. Although I'd still argue that this is not the correct architecture

2022-01-13 16:51 UTC, rrousselGit commented
That's undesired. Your `block` function should not be static. This would allow it to have access to the `blockGuiProvider`'s ref

Then your watchIsBlocked & debugTokens should not be functions but providers instead

```dart
static final isBlocked = Provider((ref) => ref.watch(blockGuiProvider).isNotEmpty);
```

2022-01-13 17:15 UTC, PavelPZ commented
Ok, so I need to add more information to my example. In my new project, I try to use the unique features of Riverpod - independence from Flutter.

I try to create all application state management logic as a Dart (not flutter) project. There is one global state (that's why I use Select a lot to access internal substates). Flutter navigation, login logic etc. are state driven too.

With a minimum of Mocks, it is thus possible to completely test application logic without a single widget (including asynchronously read and store data, etc.).

As a minimum, is it possible to unify ```Ref.watch``` and ```WidgetRef.watch``` syntax?

2022-01-13 17:56 UTC, rrousselGit commented
No. Ref and WidgetRef are voluntarily kept separate. If you're trying to use them interchangeably, there's an issue with your architecture

2022-01-13 18:31 UTC, PavelPZ commented
Not if I am working with state in both dart test and flutter. Following code tests blocking and unblocking GUI:

```
    final container = createContainer();
    final provider = Provider((ref) => BlockGuiState.watchIsBlocked(ref));

    final unblock1 = BlockGuiState.block(container, reason: 'test1');
    final unblock2 = BlockGuiState.block(container, reason: 'test2');
    await container.pump();
    expect(BlockGuiState.debugTokens(container), '[test1, test2]');
    expect(read(container, provider), false);

    unblock1();
    await container.pump();
    expect(BlockGuiState.debugTokens(container), '[test2]');
    expect(read(container, provider), false);

    unblock2();
    await container.pump();
    expect(BlockGuiState.debugTokens(container), '[]');
    expect(read(container, provider), true);
```

2022-01-13 18:35 UTC, PavelPZ commented
Following hack is working for me:

```
typedef UniversalRef = dynamic;

T read<T>(UniversalRef ref, ProviderBase<T> source) {
  if (ref is ProviderContainer)
    return ref.read(source);
  else if (ref is Ref)
    return ref.read(source);
  else 
  // TODO(pz): extend code for WidgetRef in Flutter
    throw Exception();
}

T watch<T>(UniversalRef ref, AlwaysAliveProviderListenable<T> source) {
  if (ref is ProviderContainer)
    throw Exception();
  else if (ref is Ref)
    return ref.watch(source);
  else
  // TODO(pz): extend code for WidgetRef in Flutter
    throw Exception();
}
```

2022-01-13 18:42 UTC, rrousselGit commented
Like I said, your architecture is incorrect. `debugTokens`/`watchIsBlocked` should be providers, and `block` should be a method not a static function

You're having this issue because of this. If you fix those like suggested, you won't need a shared interface

2022-01-13 21:47 UTC, PavelPZ commented
Ok, thanks, I will try it.
In general, I'm excited about the riverpod, thanks a lot for it.